# Site settings
title: mas863.14 notes
email: weller@mit.edu
author: Tomer Weller
description: "How to make (almost) anything class notes by Tomer Weller "
baseurl: "/classes/863.14/people/tomer_weller"
url: "http://fab.cba.mit.edu"
google_analytics: 
animated: false
show_related_posts: false


# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
sass:
  compressed: true
